on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello by puru
    steps:
      - name: Hello world action step
        id: hello
        uses: puru-khedre/puru-khedre/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Purushottam Khedre'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
